name: Health CheckUp

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute

jobs:
  run:
    runs-on: ubuntu-latest  # Specify the operating system

    steps:
      - name: Run Bash Script
        run: |
          #!/bin/bash

          URL="https://social-media-9nzi.onrender.com/"  # Replace with the URL you want to check

          while true; do
            # Check website status
            response=$(wget --quiet -O /dev/null --server-response $URL 2>&1 | tail -n 1)
            # Extract status code from response (may require adjustment based on wget version)
            status_code=${response##* }

            # Print status message based on response code
            if [[ $status_code == 200 ]]; then
              echo "$(date): $URL is up!"
            else
              echo "$(date): $URL is down! Status code: $status_code"
            fi

            # Wait for 4 minutes (240 seconds)
            sleep 240
          done
          
          echo "This is a Bash command"
          ls -l
