name: Health CheckUp

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute

jobs:
  run:
    runs-on: ubuntu-latest  # Specify the operating system

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version you want

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          # Add any other dependencies here, e.g., pip install requests

      - name: Run script
        run: python ../main.py
