name: Health CheckUp

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute

jobs:
  run:
    runs-on: ubuntu-latest

  steps:
    - name: Set up Python
      with:
        python-version: '3.8'  # Specify the Python version you want

    - name: Install dependencies
      run: |
          pip install --upgrade pip
          # Add any other dependencies here, e.g., pip install requests

    - name: Run script
      run: python main.py
