name: Run Python Script Every Minute

on:
  schedule:
    # Runs every minute
    - cron: "*/1 * * * *"

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (if you need to access any files from it)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run the Python script located in the home directory
      - name: Run Python script
        run: |
          python ./main.py
